# Uncomment this line to define a global platform for your project
# platform :macos, ’10.11’
use_frameworks!

target 'eCompleteContact' do	
    pod 'RxSwift',    '3.0.0-rc.1'
    pod 'RxCocoa',    '3.0.0-rc.1'
    pod 'SwiftyJSON', '3.1.1'
    pod 'Alamofire',  '4.0'
    pod 'RxAlamofire', '3.0.0-rc.1'
    pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.11'
    end
  end
end
